// Bridge to the Rust implementation via NAPI-RS
// This will be generated by the build process

export interface RuneBridgeInstance {
  initialize(configJson: string): Promise<void>;
  start(): Promise<void>;
  stop(): Promise<void>;
  search(queryJson: string): Promise<string>;
  getStats(): Promise<string>;
  reindex(): Promise<void>;
  echo(message: string): Promise<string>;
}

export interface RuneBridgeConstructor {
  new (): RuneBridgeInstance;
}

// The actual bridge implementation will be loaded from the .node file
let bridge: RuneBridgeConstructor;

try {
  // Try to load the built native module
  bridge = require('../rune-bridge.darwin-arm64.node').RuneBridge;
} catch (e) {
  try {
    // Fallback to other architectures
    bridge = require('../rune-bridge.node').RuneBridge;
  } catch (e2) {
    // If the native module isn't built yet, provide a mock implementation
    console.error('Native bridge not found. Please run "npm run build:bridge" first.');

    // Mock implementation for development
    class MockRuneBridge {
      async initialize(configJson: string): Promise<void> {
        console.error('Mock: Initializing with config:', configJson);
      }

      async start(): Promise<void> {
        console.error('Mock: Starting engine');
      }

      async stop(): Promise<void> {
        console.error('Mock: Stopping engine');
      }

      async search(queryJson: string): Promise<string> {
        console.error('Mock: Searching with query:', queryJson);
        return JSON.stringify({
          query: JSON.parse(queryJson),
          results: [],
          total_matches: 0,
          search_time_ms: 0,
        });
      }

      async getStats(): Promise<string> {
        console.error('Mock: Getting stats');
        return JSON.stringify({
          indexed_files: 0,
          total_symbols: 0,
          index_size_bytes: 0,
          cache_size_bytes: 0,
        });
      }

      async reindex(): Promise<void> {
        console.error('Mock: Reindexing');
      }

      async echo(message: string): Promise<string> {
        return `Mock echo: ${message}`;
      }
    }

    bridge = MockRuneBridge as unknown as RuneBridgeConstructor;
  }
}

export const RuneBridge = bridge;
